# Site settings
title: pebble {code}
baseurl: "http://pebblecode.com" # the subpath of your site, e.g. /blog/
url: "http://pebblecode.com" # the base hostname & protocol for your site

params:
  description: Digital Innovation Consultancy - Agile Development, Design Thinking and Rapid Prototyping.

  email: hello@pebblecode.com
  twitter: pebblecode
  github: pebblecode
  vimeo: pebblecode


# Pagination
# paginate: 8
# paginate_path: "/blog/:num"
#
# relative_permalinks: false

#tag blog posts for analytics
# defaults:
#   -
#     scope:
#       path: ""
#       type: "post"
#     values:
#       analytics_category: "blog"
