---
layout: post
title: The present and the future of Data Visualisation
date: '2015-01-30T12:10:00+00:00'
tags:
- dataviz design visualization data
tumblr_url: http://blog.pebblecode.com/post/109573478461/the-present-and-the-future-of-data-visualisation
author: John Mildinhall
---
<p><b>Attractive versus Informative</b></p><blockquote><p>&ldquo;Beauty is truth, truth beauty,&rdquo; – that is all Ye know on earth, and all ye need to know.</p><p>John Keats. <i>Ode on a Grecian Urn</i></p></blockquote>
<p>Data visualisation stems from two broad traditions. The first tradition is <i>academic</i>, where economists, scientists and statisticians have sought to display complex findings and ideas in a succinct and easily digestible manner for an audience of academic peers. The second tradition is <i>journalistic</i>, where communicators initially sought additional colour and insight to add to their articles and arguments for an audience of the general public. Where these two differ significantly in their approach is in the focus of their efforts: Academics have valued minimalism, brevity and standardisation. Journalists have above all valued attention, but also clarity, impact and memorability. </p><!-- more -->
<p><img src="https://31.media.tumblr.com/1f6be6700023a00ca73fd3d04866c4dc/tumblr_inline_niwacbobJN1svon23.png" alt="image"/></p>

<p><i>1. An example of academic visualisation - the Remote Distractor Effect (Walker, Deubel, Schneider &amp; Findlay, 1997).</i></p>
<p><i><img src="https://31.media.tumblr.com/f2fdf89fc5d39463c444d591adbf27d7/tumblr_inline_niwbgm0A8c1svon23.jpg" alt="image"/></i></p>

<p><i>2. An example of journalistic visualisation - Bumps, Bruises and Breaks in the NFL. At a glance the viewer can determine that knees are most commonly injured in the NFL (Wall Street Journal).</i></p>


<p>There are two titans of academic visualisation, the statisticians <a href="http://en.wikipedia.org/wiki/John_Tukey">John Tukey</a> and <a href="http://en.wikipedia.org/wiki/Edward_Tufte">Edward Tufte</a>. Tukey advocated visualisation as a method for <a href="http://www.itl.nist.gov/div898/handbook/eda/eda.htm">exploring data</a>, rather than merely supporting or rejecting hypotheses. Among his inventions are the boxplot, and the use of the term &lsquo;bit&rsquo; in computing. Tufte&rsquo;s seminal book <i>Quantitative Data Visualisation </i>(1983) emphasised absolute efficiency in visualising data, arguing that a minimal use of 'data-ink&rsquo; is self-evidently beneficial.</p>
<p><img src="https://31.media.tumblr.com/8bff0cbe415f81beb5331691d92eb753/tumblr_inline_niw9yciDfC1svon23.png" alt="image"/></p>
<p><i>3. A Tukey </i><i>Boxplot showing the 1st, 2nd and 3rd quartiles, the 2nd and 98th percentiles, as well as outliers in the <a href="http://en.wikipedia.org/wiki/Michelson%E2%80%93Morley_experiment">Michelson-Moreley</a> experiment.</i></p>
<p><i><img src="https://31.media.tumblr.com/5588e491d78f9a045a7f391b1f4d8190/tumblr_inline_niwawrgdNP1svon23.png" alt="image"/></i></p>


<p><i>4. A Tukey visualisation displaying relative changes in magnitude and order between two dates. All extraneous information has been removed, leaving only 'data ink&rsquo;.</i></p>
<p>Despite the many suggestions of novel and improved graphical representations of scientific, engineering and economic data, few of these have actually been taken up by the academic community. The inherent conservatism of scientific journals have upheld highly traditional visualisations that have not taken advantage of modern technology and that are essentially still stuck in the analogue age. </p>
<p>The history of journalistic visualisation is a long one; The oldest examples date to the 18th and 19th centuries - such as Charles Joseph Minard&rsquo;s infographic of Napoleon&rsquo;s disastrous Russian campaign (see figure 6), the timelines of <a href="http://hyperstudio.mit.edu/blog/blog-research/timeline-visualizations-a-brief-and-incomplete-teleological-history-part-1/">Joseph Priestley</a> (discoverer of Oxygen and inventor of Soda Water) and the line and bar charts of William Playfair. More recent work such as <a href="http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0002w4&amp;topic_id=1&amp;topic=">Megan Jaegerman&rsquo;s</a> work for the New York Times demonstrate how powerful journalistic visualisation can be for communicating complex issues.</p>
<p>The journalistic tradition was populist - some of the earliest published works of visualisation became best sellers. The producers vied with each other to become more and more bombastic, as they came to the realisation that they were in competition for the attention of readers. Transgressions of good visualisation were first held to account by Darrell Huff&rsquo;s 1954 work <a href="http://www.amazon.co.uk/How-Lie-Statistics-Penguin-Business/dp/0140136290"><i>How to Lie with Statistics</i></a>. Still a model of accessibility and clarity, Huff &rsquo;s book categorised examples of how producers of visualisations misled their readers (sometimes intentionally, sometimes not) by violating principles of graphical data presentation. These included truncation of axes, inappropriately scaled two-dimensional objects representing one-dimensional data, and arbitrary choices of statistical averages that misrepresent the underlying data. </p>
<p><img src="https://31.media.tumblr.com/303a158190aed4d1a15d1a58f78d15d4/tumblr_inline_niwbjhrObD1svon23.png" alt="image"/></p>

<p><i>5. A poor example of journalistic visualisation - an inappropriate choice of representing non-related data as a proportion of a whole, as well as depicting linear quantities as two-dimensional areas.</i></p>
<p>The excesses of journalistic visualisation are <a href="http://viz.wtf">still with us today</a>. Despite some <a href="http://www.pewresearch.org/fact-tank/2014/12/29/our-favorite-pew-research-center-data-visualizations-from-2014/">excellent examples</a> becoming more prevalent in recent years, we still see a seemingly unending stream of poorly labelled axes, inappropriate scalings and superfluous use of 3D elements. </p>
<p>These two traditions in visualisations reflect the sometimes troubled relationship between truth and beauty. The truest representation is often diminished by attempts to make it beautiful, and aesthetic considerations can be ruined by the difficulty of using real-world data. Academic visualisation is not attractive, and as such has an extremely limited audience. Journalistic visualisation has promoted attention-grabbing flashiness at the expense of accuracy and fair representations of underlying data. </p>
<p><b>Monologue versus Dialogue</b></p>
<blockquote>
Words!
Pens are too light.
Take a chisel to write. </blockquote><blockquote> Basil Bunting. <i>Briggflats</i>
</blockquote>
<p>Traditional visualisation is essentially an asynchronous medium. The producers of graphics and charts laboured long hours to create a clean version of their depiction of the data. Often hand-drawn, these would appear in print publications, or would be photographed and developed into slides. While this was simply a consequence of the technological limitations of the time, the barrier to creation also leant gravitas to the visualisations. Knowledge that the creation of a beautiful graph displaying rich data would have taken hours if not days implicitly communicated the notion that the creator would have taken the trouble to get the data right. </p>
<p><img src="https://31.media.tumblr.com/57db2afbec07235c26d730371a7835b2/tumblr_inline_niwbohzmb21svon23.png" alt="image"/></p>

<p><i>6. Minard&rsquo;s depiction of Napoleon&rsquo;s Russian Campaign of 1812 is a classic example of the gravitas that a laboriously produced hand-drawn visualisation provided.</i></p>
<p>The arrival of graphical plotting software such as S, R, Matlab and Excel have reduced the amount off effort required to produce usable graphs to a trivial level. This in turn has led to a situation where the producer of a graph has great power (to produce an innumerable amount of graphs) but no responsibility to demonstrate how and why they used their data. As Tufte noted in his essay &ldquo;<a href="http://users.ha.uth.gr/tgd/pt0501/09/Tufte.pdf">The cognitive style of PowerPoint</a>&rdquo;, the graph and its attendant presentation is still used in a primarily didactic mode where the presenter broadcasts their message to a passive audience. </p>
<p>Graphs are and have always been talking points. They are a distillation of a message that would otherwise be hidden in raw data, but often the message is still too rich for useful communication to be one-way alone. We are now in the possession of design patterns that allow us to interact usefully and collaboratively with data, but the gold standard of truth in organisations is still PowerPoint. </p>
<p>We are in a position to provide audiences with the means to co-explore with us what we have created, yet this is a relatively rare occurrence. Providing the means to make data exploration a dialogue represents a huge area of opportunity for those of us in the technology business. </p>
<p><b>Conservative versus Progressive</b></p>
<p>The pervasiveness of Office as a visualisation tool (Excel to create, PowerPoint to communicate) has led to a standard language of line, bar and pie charts. Well used, these can be effective in certain cases, but the clarity provided can also cage the viewer&rsquo;s thought. Data often need to be manipulated heavily to fit into these tools, and the use of binning, indices of central tendency and surrogate measures all give plenty of opportunity to deceive the reader. </p>
<p><img src="https://31.media.tumblr.com/7e030279692f67b0ba2de36f659865f3/tumblr_inline_nixq16vBA21svon23.png" alt="image"/></p>

<p><i>7. An example of Excel &ldquo;chart junk&rdquo;. The use of three dimensions inhibits the viewer&rsquo;s ability to understand the data. Data points are obscured by others, and fine discriminations are simply not possible. The use of labels is an admittance of the ineffectiveness of this visualisation, and adds further clutter. </i></p>
<p>The standard visualisation tools are also not necessarily best at the job they were designed for. Angular differences are hard to distinguish, meaning that pie charts are a <a href="https://www.stevefenton.co.uk/Content/Pie-Charts-Are-Bad/">poor choice</a> for judging relative proportions. Standard axes in line charts are arguably worse than the frame ranges and tick marks that Tufte proposed.</p>
<p><img src="https://31.media.tumblr.com/f6a1d9d383654d85050d9d7e1e3c996c/tumblr_inline_nixpvynlMv1svon23.png" alt="image"/></p>

<p><i>8. Tufte proposed adding tick marks to axes, allowing the user to judge distribution along a single dimension at the same time as visualising the correlation between two dimensions</i></p>
<p>A pervasive heuristic amongst data visualisation aficionados is that three-dimensional visualisation should be avoided. This is still the case for static visualisations, but the advances in technology in 3D visualisation are starting to make that heuristic <a href="http://www.nytimes.com/interactive/2015/01/09/sports/the-dawn-wall-el-capitan.html">look shaky</a>. Virtual reality tech such the <a href="https://www.youtube.com/watch?v=JX0W6nuLxUE">Oculus Rift</a>, along with nascent attempts to <a href="http://blog.bitops.com/blog/2014/07/31/css-and-vr-integration/">extend HTML and CSS to the 3D realm</a> raise the real possibility that the time has come for immersive visualisation. </p>
<p>The advent of cheap 3D printing has also facilitated a more tangible sort of visualisation. A physical object brings many benefits such as effortless manipulation, a presence that draws attention to itself, and persistence (it&rsquo;s not hidden in a book, and doesn&rsquo;t need electricity to remain viewable). This is one of the ways that data visualisations are becoming more accessible to lay viewers.</p>
<p><img src="https://31.media.tumblr.com/ec56b4cb0f7fec00cfef772f8b640deb/tumblr_inline_nixqi7h1Hi1svon23.jpg" alt="image"/></p>

<p><i>8. 3D printed representation of 24 hours of physical activity (Susan Morris)</i></p>
<p><b>What needs to happen to data visualisation now</b></p>
<p>In the last few years technology has vastly reduced the barriers to producing fantastic visualisations. The possibilities of smooth and intuitive interaction models, adequate and mature 3D visualisation, and novel display methods combine to indicate a few ways forwards:</p>
<ul><li>Stop relying on old-fashioned, static, 1-way methods of communicating data visualisations. The Excel/PowerPoint graphic should die soon.</li>
<li>Use interactions to let the viewer set the level of complexity at which they are comfortable. &ldquo;Zoomable&rdquo; data visualisation lets the user determine for themselves whether choices such as mean or median are appropriate to understanding the bigger picture, and they do this without forcing clutter on the user. </li>
<li>Use technology to improve the attention-grabbing properties of visualisation. What is the use of a graphic if no-one looks at it in the first place? Academics have a moral obligation to disseminate their findings not just to other academics, but to the wider public. By maintaining current conservative and arcane data visualisation practices we are missing an opportunity for wider engagement with complex ideas.</li>
<li>Bring data visualisation into the physical realm. A physical presence simply has more of a shot at engaging people at depth. Harder to create maybe, but all the more impressive for it. </li>
<li>Design for dialogue rather than monologue. We should not be foghorning our findings, but initiating conversations. The intellectually honest practitioner should provide a narrative and a commentary, but be sufficiently confident to not hide their working, or deny people access to the underlying data. There are always many ways to interpret data, and this should be reflected in the way we create, communicate and consume our visualisations.</li></ul>
